#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404
# page that contains the string Ceci n'est pas une page.

#get updates
sudo apt-get -y update

#install nginx
sudo apt-get -y install nginx

#nginx start
sudo service nginx start

# allow http for nginx
sudo ufw allow "Nginx Http"

#creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# create an error404.html file
echo "ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# using sed command to perform redirections

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/oleweps permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# custom HTTP header
sudo sed -i "/server_name _/a add_header x-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# testing configurations for syntax errors
sudo nginx -t

# restart nginx
sudo service nginx restart;
