#!/usr/bin/env bash
# Script to setup and install HaProxy

sudo apt-get -y update
sudo apt-get -y install haproxy

echo '
frontend olewepsdev.tech
    bind *:80
    mode http
    default_backend oleweps_backed

backend oleweps_backed
    balance roundrobin
    server 337116-web-02 54.209.171.151:80 check
    server 337116-web-01 34.202.158.122:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start
